### ISSUE TITLE
可以来个完整的jQuery插件编写教程呢？

### ISSUE THREAD

**Issue by niaiwomattt** [songjinzhong/JQuerySource#2]
网上的我总感觉写的不通俗，而且代码也不规范。曾经见过一个很牛的，但是现在找不到了。不胜感激！

**Comment by songjinzhong** [comment]
不好意思，现在才看到。
现在 jQuery 已经被一些主流的框架取代了，写插件的话，主要用 extend 函数来扩展，按照需要看下是在原型链上扩展还是在 jQuery 上扩展，原型链上的扩展：
```
$.fn.extend({
  yourFunc: function(){
    ......
  }
})
```
使用：
```
$('#example').youFunc()
```

**Comment by niaiwomattt** [comment]
谢谢，我已经写了一个了！不过很多公司还在用jQuery。
