### ISSUE TITLE
放到gitbook吧

### ISSUE THREAD

**Issue by niaiwomattt** [songjinzhong/JQuerySource#3]
看你结构应该是弄过gitbook吧 ？如果没有很简单，按你这个加个目录文件就行了！如果有gitbook就把gitbook的地址也放到 readme 里呗！有利于大家阅读分享，而且你可以跟出版社联系联系，说不定还能出版书！

**Comment by songjinzhong** [comment]
现在学 jQuery 纯属是为了巩固前端技能，react、vue 等主流的框架才是现在前端应该熟练掌握的。
